import { useEffect, Key } from 'react'

import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { useSelector, useDispatch } from 'react-redux'
import {
	fetchMovies,
	deleteMovie,
	selectMovies,
	like,
	dislike,
} from '@/slices/movieSlice'
import { AppDispatch } from '@/store'

export default function Home() {
	const { movies } = useSelector(selectMovies)
	const dispatch = useDispatch<AppDispatch>()

	useEffect(() => {
		dispatch(fetchMovies())
		console.log('rerendered')
	}, [dispatch])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>Movies:</h1>
				<ul>
					{movies.map((movie, index) => (
						<li key={index}>
							<p onClick={() => dispatch(deleteMovie(movie.id))}>
								{JSON.stringify(movie)}
							</p>{' '}
							<span onClick={() => dispatch(like(movie.id))}>
								{' '}
								+{' '}
							</span>{' '}
							<span onClick={() => dispatch(dislike(movie.id))}>
								{' '}
								-{' '}
							</span>
						</li>
					))}
				</ul>
			</main>
		</>
	)
}
