import { useEffect, Key } from 'react'

import Head from 'next/head'
import Card from '@/components/Card'
import styles from '@/styles/Home.module.css'

import { useSelector, useDispatch } from 'react-redux'
import { fetchMovies, selectMovies } from '@/slices/movieSlice'
import { AppDispatch } from '@/store'
import Navbar from '@/components/Navbar'

export default function Home() {
	const { movies, loading } = useSelector(selectMovies)
	const dispatch = useDispatch<AppDispatch>()

	useEffect(() => {
		dispatch(fetchMovies())
	}, [dispatch])

	if (loading) return <h1>Loading...</h1>

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<main className={styles.main + ' pt-36 max-sm:pt-64'}>
				<div className="flex flex-wrap justify-evenly items-stretch gap-x-4 gap-y-16">
					{movies.map((movie, index) => (
						<Card data={movie} key={index} />
					))}
				</div>
			</main>
		</>
	)
}
